import re
from pathlib import Path

from langchain.agents import create_agent
from langchain.messages import SystemMessage, HumanMessage
from langchain_mcp_adapters.client import MultiServerMCPClient

from weave_cv.language_models.index import get_model
from weave_cv.schemas.cv_analysis import CVProfile
from weave_cv.schemas.generation import GeneratedResumeBody
from weave_cv.schemas.jd_analysis import JobDescriptionAnalysis
from weave_cv.services.impl.tex_service_impl import TexServiceImpl

mcp_client = MultiServerMCPClient({
    "resume_generation": {
        "transport": "stdio",
        "command": "python",
        "args": ["src/weave_cv/mcp/resume_generation.py"]
    }
})


async def _get_prompt() -> SystemMessage:
    prompt = await mcp_client.get_prompt("resume_generation", "prompt")
    return SystemMessage(content=prompt[0].content)


async def make_resume_generation_agent():
    prompt = await _get_prompt()
    return create_agent(
        model=get_model(),
        system_prompt=prompt,
        response_format=GeneratedResumeBody,
        name="Resume-Generation"
    )


def _split_preamble_and_body(tex_str: str) -> tuple[str, str]:
    """Deterministic — no LLM involved, so the preamble (macro
    definitions, packages, margins) is reproduced byte-for-byte with zero
    risk of corruption. Only the body is regenerated by the model."""
    start = tex_str.find(r"\begin{document}")
    end = tex_str.find(r"\end{document}")
    if start == -1 or end == -1:
        raise ValueError("master tex file is missing \\begin{document}/\\end{document}")
    preamble = tex_str[:start]
    body = tex_str[start + len(r"\begin{document}"):end].strip()
    return preamble, body


def _safe_filename(name: str | None, jd_analysis: JobDescriptionAnalysis | None) -> str:
    if not name:
        return "resume"
    if not jd_analysis:
        return "resume"
    safe_name = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_")
    company_name = jd_analysis.company_name or "company"
    title = jd_analysis.title or "job_title"
    safe_company = re.sub(r"[^A-Za-z0-9]+", "_", company_name).strip("_")
    safe_title = re.sub(r"[^A-Za-z0-9]+", "_", title).strip("_")
    from datetime import datetime
    time = datetime.now().strftime("%d %b %Y")
    safe = f"{safe_name}_{safe_company}_{safe_title}_{time}"
    return safe or "resume"


_LATEX_ESCAPE_MAP = {
    "&": r"\&",
    "%": r"\%",
    "#": r"\#",
    "_": r"\_",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}
_UNESCAPED_SPECIAL_RE = re.compile(r"(?<!\\)([&%#_~^])")


def _escape_latex_specials(text: str) -> str:
    """Deterministic backstop for the prompt's escaping rule, which the
    model doesn't reliably follow (e.g. it left a bare '&' in "Observability
    & Data Visualization" once, which is a hard LaTeX compile error, not a
    cosmetic issue). Only touches characters that are never meaningful as
    macro-call syntax in this template — never braces or backslashes,
    which are structural to the \\resumeItem{...}-style calls the model
    emits and would corrupt every macro if escaped. Skips anything already
    escaped (preceded by a backslash) so it can't double-escape text the
    model got right on its own.

    Deliberately excludes '$': this template's own \\resumeProjectHeading
    convention uses bare $|$ as a math-mode divider glyph between a
    project's name and its tech stack, reproduced from the reference body
    on every project entry. Auto-escaping '$' turned that into literal
    "$|$" text — a guaranteed regression on every run with projects,
    worse than leaving the rare literal-dollar-amount-in-a-bullet case to
    the prompt's instruction instead of a deterministic fix.
    """
    return _UNESCAPED_SPECIAL_RE.sub(lambda m: _LATEX_ESCAPE_MAP[m.group(1)], text)


async def generate_resume(
    cv_profile: CVProfile, master_tex_path: str, output_dir: str,
    jd_analysis: JobDescriptionAnalysis | None
) -> tuple[str, str]:
    """Generate a tailored resume from cv_profile, reusing master_tex_path's
    template, and save it as .tex + .pdf in output_dir. Returns
    (tex_path, pdf_path). output_dir is created if it doesn't exist —
    where it comes from (CLI flag, prompt, hardcoded test path, ...) is
    the caller's concern, not this function's or the agent's."""
    with open(master_tex_path, "r", encoding="utf-8") as f:
        master_tex = f.read()
    preamble, reference_body = _split_preamble_and_body(master_tex)

    agent = await make_resume_generation_agent()
    response = await agent.ainvoke({
        "messages": [
            HumanMessage(content=(
                "Generate a new LaTeX document body for the CVProfile below, "
                "using the reference body as your formatting/macro guide.\n\n"
                f"CVProfile:\n{cv_profile.model_dump_json(indent=2)}\n\n"
                "Reference body (from the master resume template — for "
                f"formatting/macro style only, its content is not yours to "
                f"reuse):\n{reference_body}"
            ))
        ]
    })

    generated: GeneratedResumeBody = response["structured_response"]
    escaped_body = _escape_latex_specials(generated.tex_body)

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    full_tex = f"{preamble}\\begin{{document}}\n{escaped_body}\n\\end{{document}}\n"

    filename = _safe_filename(cv_profile.contact.name, jd_analysis)
    tex_path = Path(output_dir) / f"{filename}.tex"
    tex_path.write_text(full_tex, encoding="utf-8")

    pdf_path = Path(output_dir) / f"{filename}.pdf"
    tex_service = TexServiceImpl()
    if tex_service.tex_to_pdf(tex=full_tex, output_path=str(pdf_path)) is None:
        raise ValueError("Generated tex failed to compile to PDF.")

    return str(tex_path), str(pdf_path)
