import re
from datetime import datetime
from pathlib import Path

from langchain.agents import create_agent
from langchain.messages import SystemMessage, HumanMessage
from langchain_mcp_adapters.client import MultiServerMCPClient

from weave_cv.language_models.index import get_model
from weave_cv.mcp import mcp_script_path
from weave_cv.schemas.cv_analysis import CVProfile
from weave_cv.schemas.generation import GeneratedResumeBody
from weave_cv.schemas.jd_analysis import JobDescriptionAnalysis
from weave_cv.services.impl.tex_service_impl import TexServiceImpl

mcp_client = MultiServerMCPClient({
    "resume_generation": {
        "transport": "stdio",
        "command": "python",
        "args": [mcp_script_path("resume_generation.py")]
    }
})


async def _get_prompt() -> SystemMessage:
    prompt = await mcp_client.get_prompt("resume_generation", "prompt")
    return SystemMessage(content=prompt[0].content)


async def make_resume_generation_agent():
    prompt = await _get_prompt()
    return create_agent(
        model=get_model(),
        system_prompt=prompt,
        response_format=GeneratedResumeBody,
        name="Resume-Generation"
    )


def _split_preamble_and_body(tex_str: str) -> tuple[str, str]:
    """Deterministic — no LLM involved, so the preamble (macro
    definitions, packages, margins) is reproduced byte-for-byte with zero
    risk of corruption. Only the body is regenerated by the model."""
    start = tex_str.find(r"\begin{document}")
    end = tex_str.find(r"\end{document}")
    if start == -1 or end == -1:
        raise ValueError("master tex file is missing \\begin{document}/\\end{document}")
    preamble = tex_str[:start]
    body = tex_str[start + len(r"\begin{document}"):end].strip()
    return preamble, body


def _strip_comments(text: str) -> str:
    """Comments (e.g. a "%---- HEADER ----%" section-divider banner) are
    pure decoration for a human editing the raw .tex source — they never
    affect the rendered PDF, so there's no reason the generation agent
    needs to see them in the reference body it's shown. Left in, the
    model tends to imitate that banner style in its own output to "match
    the reference," which is exactly the failure mode
    _escape_latex_specials' docstring already describes: a comment it
    adds becomes live, uncommented LaTeX once its own unescaped '%' gets
    escaped downstream by that function. Stripping comments from what
    the model even sees closes the loophole at the source, instead of
    only telling it not to reproduce them (still done too, in the
    prompt, as a second layer — this is the reliable one).
    """
    lines = (re.sub(r"(?<!\\)%.*$", "", line) for line in text.splitlines())
    return "\n".join(lines).strip()


# Known tectonic-incompatible preamble patterns, fixed deterministically
# rather than by asking an LLM to edit the preamble. The preamble is
# reused byte-for-byte on purpose (see _split_preamble_and_body's
# docstring) — an LLM "fixing" it risks silently altering packages,
# margins, or macro definitions the body's \resumeItem{...}-style calls
# depend on, with no equivalent of the CVProfile stable-ID diff to catch
# it if it does. This handles the one recurring, well-understood class of
# preamble breakage instead: pdfTeX-only primitives
# (\pdfglyphtounicode/\pdfgentounicode, used by many resume templates for
# copy-paste text fidelity) that tectonic's engine doesn't implement at
# all, which has now broken two different master resumes in this project
# the same way. Guarding them is a no-op everywhere else — it only
# changes behavior on engines that lack these primitives.
#
# fontawesome5's icon fonts crash tectonic's XeTeX engine outright
# (SIGABRT) merely on \usepackage, before any \fa... glyph is even used —
# not a recoverable LaTeX error, so there's no compiler message to retry
# against. The legacy fontawesome (v4) package renders the same common
# icon names (\faPhone, \faEnvelope, \faLinkedin, \faGithub, ...) without
# tripping the crash, so swapping the package is a safe substitution:
# fontawesome5 never compiles under tectonic regardless, so there's no
# working behavior this could regress. A master resume using a
# v5-only icon absent from v4 will surface as an ordinary "Undefined
# control sequence" on retry instead of an unrecoverable crash — strictly
# more actionable than today's outcome either way.
_PREAMBLE_SANITIZERS: list[tuple[re.Pattern, str]] = [
    (
        re.compile(r"^\\input\{glyphtounicode\}[ \t]*$", re.MULTILINE),
        r"\\ifdefined\\pdfgentounicode\\input{glyphtounicode}\\fi",
    ),
    (
        re.compile(r"^\\pdfgentounicode=1[ \t]*$", re.MULTILINE),
        r"\\ifdefined\\pdfgentounicode\\pdfgentounicode=1\\fi",
    ),
    (
        re.compile(r"\\usepackage(\[[^\]]*\])?\{fontawesome5\}"),
        r"\\usepackage{fontawesome}",
    ),
]


def _sanitize_preamble(preamble: str) -> str:
    """Applies _PREAMBLE_SANITIZERS. Idempotent — a preamble that's
    already guarded (or never had the pattern) matches nothing and
    passes through unchanged, so this is safe to run unconditionally on
    every call rather than needing a one-time fixup step."""
    for pattern, replacement in _PREAMBLE_SANITIZERS:
        preamble = pattern.sub(replacement, preamble)
    return preamble


_TECTONIC_ERROR_LOCATION_RE = re.compile(r"error:\s*([^\s:]+):(\d+):")


def _error_is_body_attributable(error_output: str, body_start_line: int) -> bool:
    """True if a compile error is plausibly something the generation
    agent's own output caused — i.e. worth spending another attempt (a
    real LLM call) on. False if it's clearly a preamble/template-level
    problem instead: an error inside a file the preamble \\input's (e.g.
    tectonic reports "glyphtounicode:7: ..." — a different file
    entirely, not the document being compiled), or a line number that
    falls before the body even starts. Retrying body generation can
    never fix either case, since the agent never touches the preamble —
    the exact same error would recur on every attempt.

    Defaults to True (retry) when tectonic's error text doesn't cite a
    parseable file:line at all — some failure modes (e.g. brace-matching
    running off the end of the document) don't. Treating "can't tell" as
    retry-worthy preserves the pre-existing behavior for that case
    rather than risking giving up early on a genuinely fixable body
    issue just because its error happened not to include a location.
    """
    match = _TECTONIC_ERROR_LOCATION_RE.search(error_output)
    if not match:
        return True

    filename, line_str = match.group(1), match.group(2)
    if filename != "input.tex":
        return False

    return int(line_str) >= body_start_line


def _slugify(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", text).strip("_")


def _safe_filename(master_tex_path: str, jd_analysis: JobDescriptionAnalysis | None) -> str:
    """master_resume_name + company_name + timestamp. Uses the master
    .tex file's own name, not the CVProfile's contact.name — the file
    naming is about which template/run produced this output, not who the
    resume belongs to. Timestamp is full date+time with microseconds
    (not date-only, not second-only) and has no spaces: a date-only name
    collides on same-day reruns against the same company (silently
    overwriting the earlier file), and even second-only precision isn't
    safe once jobs genuinely run in parallel (agents/orchestrator_agent.py
    can run several pipelines concurrently via cli.py's `batch` command —
    two same-company jobs finishing generation in the same second would
    otherwise collide). A space in the filename is also fragile for
    shell scripting/globbing."""
    master_name = _slugify(Path(master_tex_path).stem) or "resume"
    company_name = _slugify(jd_analysis.company_name) if jd_analysis and jd_analysis.company_name else "company"
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    return f"{master_name}_{company_name}_{timestamp}"


_LATEX_ESCAPE_MAP = {
    "&": r"\&",
    "%": r"\%",
    "#": r"\#",
    "_": r"\_",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}
_UNESCAPED_SPECIAL_RE = re.compile(r"(?<!\\)([&%#_~^])")


def _escape_latex_specials(text: str) -> str:
    """Deterministic backstop for the prompt's escaping rule, which the
    model doesn't reliably follow (e.g. it left a bare '&' in "Observability
    & Data Visualization" once, which is a hard LaTeX compile error, not a
    cosmetic issue). Only touches characters that are never meaningful as
    macro-call syntax in this template — never braces or backslashes,
    which are structural to the \\resumeItem{...}-style calls the model
    emits and would corrupt every macro if escaped. Skips anything already
    escaped (preceded by a backslash) so it can't double-escape text the
    model got right on its own.

    Deliberately excludes '$': this template's own \\resumeProjectHeading
    convention uses bare $|$ as a math-mode divider glyph between a
    project's name and its tech stack, reproduced from the reference body
    on every project entry. Auto-escaping '$' turned that into literal
    "$|$" text — a guaranteed regression on every run with projects,
    worse than leaving the rare literal-dollar-amount-in-a-bullet case to
    the prompt's instruction instead of a deterministic fix.
    """
    return _UNESCAPED_SPECIAL_RE.sub(lambda m: _LATEX_ESCAPE_MAP[m.group(1)], text)


MAX_GENERATION_ATTEMPTS = 3


def _build_generation_instruction(
    cv_profile: CVProfile, reference_body: str, feedback: str | None
) -> str:
    instruction = (
        "Generate a new LaTeX document body for the CVProfile below, "
        "using the reference body as your formatting/macro guide.\n\n"
        f"CVProfile:\n{cv_profile.model_dump_json(indent=2)}\n\n"
        "Reference body (from the master resume template — for "
        f"formatting/macro style only, its content is not yours to "
        f"reuse):\n{reference_body}"
    )
    if feedback:
        instruction += (
            "\n\nYour previous attempt did not compile. This is the real "
            "compiler error — fix whatever it's pointing at (a stray "
            "special character, an unbalanced brace, a wrong macro "
            "argument count, ...) in this attempt:\n"
            f"{feedback}"
        )
    return instruction


async def generate_resume(
    cv_profile: CVProfile, master_tex_path: str, output_dir: str,
    jd_analysis: JobDescriptionAnalysis | None
) -> tuple[str, str, int]:
    """Generate a tailored resume from cv_profile, reusing master_tex_path's
    template, and save it as .tex + .pdf in output_dir. Returns
    (tex_path, pdf_path, attempts). output_dir is created if it doesn't
    exist — where it comes from (CLI flag, prompt, hardcoded test path,
    ...) is the caller's concern, not this function's or the agent's.

    Compilation failure is retried, feeding tectonic's actual error text
    back to the model as feedback (same pattern as
    resume_tailor_agent.tailor's feedback param) — most compile failures
    are the model's own LaTeX mistakes (a stray special character it
    forgot to escape, a mismatched brace, an accidental comment — see
    _escape_latex_specials' docstring and the "never write a LaTeX
    comment" prompt rule for the specific bug class that motivated this),
    which the model can plausibly fix once it's shown the real error
    instead of a generic "it didn't work."

    This does NOT retry on a missing/undownloadable tectonic binary
    (TexServiceImpl._compile_pdf lets that exception propagate rather
    than folding it into a normal failure) — that's an environment
    problem, not a content problem, and no amount of LaTeX rewriting
    fixes it. Retrying would just burn attempts and hide the real cause.

    It also doesn't retry when the compile error is attributable to the
    preamble rather than the body — see _error_is_body_attributable.
    Known preamble incompatibilities are sanitized deterministically
    up front (_sanitize_preamble); anything else that's still a preamble
    problem fails fast on the first attempt instead of spending
    MAX_GENERATION_ATTEMPTS worth of LLM calls regenerating a body that
    was never the cause.
    """
    with open(master_tex_path, "r", encoding="utf-8") as f:
        master_tex = f.read()
    preamble, reference_body = _split_preamble_and_body(master_tex)
    preamble = _sanitize_preamble(preamble)
    reference_body = _strip_comments(reference_body)
    body_start_line = preamble.count("\n") + 2  # +1 for \begin{document}'s own line, +1 to 1-index

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    filename = _safe_filename(master_tex_path, jd_analysis)
    tex_path = Path(output_dir) / f"{filename}.tex"
    pdf_path = Path(output_dir) / f"{filename}.pdf"

    tex_service = TexServiceImpl()
    feedback: str | None = None
    last_error = ""
    full_tex = ""

    for attempt in range(1, MAX_GENERATION_ATTEMPTS + 1):
        agent = await make_resume_generation_agent()
        instruction = _build_generation_instruction(cv_profile, reference_body, feedback)

        response = await agent.ainvoke({"messages": [HumanMessage(content=instruction)]})
        generated: GeneratedResumeBody = response["structured_response"]
        escaped_body = _escape_latex_specials(generated.tex_body)
        full_tex = f"{preamble}\\begin{{document}}\n{escaped_body}\n\\end{{document}}\n"

        pdf_bytes, error_output = tex_service.tex_to_pdf_with_diagnostics(full_tex, str(pdf_path))
        if pdf_bytes is not None:
            tex_path.write_text(full_tex, encoding="utf-8")
            return str(tex_path), str(pdf_path), attempt

        last_error = error_output

        if not _error_is_body_attributable(error_output, body_start_line):
            debug_path = Path(output_dir) / f"{filename}.failed.tex"
            debug_path.write_text(full_tex, encoding="utf-8")
            raise ValueError(
                "Generated tex failed to compile because of what looks like a "
                "preamble/template problem, not the generated body — retrying "
                "wouldn't help, since the generation agent never touches the "
                f"preamble. Compiler error:\n{error_output}\n\n"
                f"The failed attempt was saved to {debug_path} for inspection. "
                "Check your master resume's preamble (packages, custom "
                "\\newcommand macros, margins)."
            )

        feedback = error_output

    # Every attempt failed to compile with a body-attributable error.
    # Save the last attempt so there's something to actually look at
    # instead of nothing — the raised error alone doesn't let anyone
    # inspect the LaTeX that broke.
    debug_path = Path(output_dir) / f"{filename}.failed.tex"
    debug_path.write_text(full_tex, encoding="utf-8")
    raise ValueError(
        f"Generated tex still failed to compile after {MAX_GENERATION_ATTEMPTS} attempts. "
        f"Last compiler error:\n{last_error}\n\n"
        f"The last failed attempt was saved to {debug_path} for inspection."
    )
